# Generated by Django 4.1.4 on 2023-06-16 15:04

import FinalApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_file',
            new_name='image_save',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=2, storage=FinalApp.models.RenameStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
