# Generated by Django 4.1.4 on 2023-06-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0002_rename_image_file_image_image_save_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_save',
        ),
    ]
