# Generated by Django 4.1.4 on 2023-06-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0006_multipleimage_remove_mymodel_images_delete_images_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
