# Generated by Django 4.1.4 on 2023-06-20 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0009_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='process_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('url_img', models.TextField()),
                ('result', models.CharField(max_length=50)),
                ('date_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='user_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='users/')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_save',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
