# Generated by Django 4.1.4 on 2023-06-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0010_process_image_user_image_image_image_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_save',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
