# Generated by Django 4.1.4 on 2023-06-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
