# Generated by Django 4.1.4 on 2023-06-23 19:47

import FinalApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0014_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_save',
            field=models.ImageField(default=2, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.ImageField(storage=FinalApp.models.RenameStoragee(), upload_to=''),
        ),
    ]
