# Generated by Django 4.1.4 on 2023-06-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0017_remove_files_file_save_alter_files_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='files/')),
                ('image2', models.ImageField(upload_to='files/')),
                ('image3', models.ImageField(upload_to='files/')),
                ('image4', models.ImageField(upload_to='files/')),
                ('image5', models.ImageField(upload_to='files/')),
            ],
        ),
    ]
