# Generated by Django 4.1.4 on 2023-06-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0018_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
        migrations.AddField(
            model_name='files',
            name='file1',
            field=models.ImageField(default='', upload_to='files/', verbose_name='File 1'),
        ),
        migrations.AddField(
            model_name='files',
            name='file2',
            field=models.ImageField(default='', upload_to='files/', verbose_name='File 2'),
        ),
        migrations.AddField(
            model_name='files',
            name='file3',
            field=models.ImageField(default='', upload_to='files/', verbose_name='File 3'),
        ),
        migrations.AddField(
            model_name='files',
            name='file4',
            field=models.ImageField(default='', upload_to='files/', verbose_name='File 4'),
        ),
        migrations.AddField(
            model_name='files',
            name='file5',
            field=models.ImageField(default='', upload_to='files/', verbose_name='File 5'),
        ),
    ]
