# Generated by Django 4.1.4 on 2023-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0019_delete_imagemodel_remove_files_file_files_file1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file4',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file5',
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.ImageField(default=2, upload_to='files/'),
            preserve_default=False,
        ),
    ]
