# Generated by Django 4.1.4 on 2023-06-23 20:54

import FinalApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0022_remove_files_image1_remove_files_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
        migrations.AddField(
            model_name='files',
            name='image',
            field=models.ImageField(default=2, storage=FinalApp.models.RenameStoragee(), upload_to='files/'),
            preserve_default=False,
        ),
    ]
