# Generated by Django 4.1.4 on 2023-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0023_remove_files_file_files_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='image',
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.ImageField(default=2, upload_to='files/'),
            preserve_default=False,
        ),
    ]
