# Generated by Django 4.1.4 on 2023-06-23 21:25

import FinalApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0024_remove_files_image_files_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(storage=FinalApp.models.RenameStorage(), upload_to='')),
                ('image_2', models.ImageField(storage=FinalApp.models.RenameStorage(), upload_to='')),
                ('image_3', models.ImageField(storage=FinalApp.models.RenameStorage(), upload_to='')),
                ('image_4', models.ImageField(storage=FinalApp.models.RenameStorage(), upload_to='')),
                ('image_5', models.ImageField(storage=FinalApp.models.RenameStorage(), upload_to='')),
                ('image_save', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
