# Generated by Django 4.1.4 on 2023-06-23 21:30

import FinalApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0025_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image_2',
            field=models.ImageField(storage=FinalApp.models.RenameStorage1(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='img',
            name='image_3',
            field=models.ImageField(storage=FinalApp.models.RenameStorage2(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='img',
            name='image_4',
            field=models.ImageField(storage=FinalApp.models.RenameStorage3(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='img',
            name='image_5',
            field=models.ImageField(storage=FinalApp.models.RenameStorage4(), upload_to=''),
        ),
    ]
