# Generated by Django 4.1.4 on 2023-06-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0026_alter_img_image_2_alter_img_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image_save',
            field=models.ImageField(upload_to='files/'),
        ),
    ]
