# Generated by Django 4.1.4 on 2023-06-23 21:34

import FinalApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0027_alter_img_image_save'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='file',
            new_name='image_save',
        ),
        migrations.AddField(
            model_name='files',
            name='image_1',
            field=models.ImageField(default='', storage=FinalApp.models.RenameStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='files',
            name='image_2',
            field=models.ImageField(default='', storage=FinalApp.models.RenameStorage1(), upload_to=''),
        ),
        migrations.AddField(
            model_name='files',
            name='image_3',
            field=models.ImageField(default='', storage=FinalApp.models.RenameStorage2(), upload_to=''),
        ),
        migrations.AddField(
            model_name='files',
            name='image_4',
            field=models.ImageField(default='', storage=FinalApp.models.RenameStorage3(), upload_to=''),
        ),
        migrations.AddField(
            model_name='files',
            name='image_5',
            field=models.ImageField(default='', storage=FinalApp.models.RenameStorage4(), upload_to=''),
        ),
    ]
