# Generated by Django 4.1.4 on 2023-06-24 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0032_alter_results_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='process_Seg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('result', models.CharField(max_length=50)),
                ('date_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
