# Generated by Django 4.1.4 on 2023-06-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0038_alter_results_content_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
