# Generated by Django 4.1.4 on 2023-06-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0041_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
