# Generated by Django 4.1.4 on 2023-06-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0043_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='image_2',
        ),
    ]
