# Generated by Django 4.1.4 on 2023-06-25 23:12

import FinalApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0044_remove_files_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='image_5',
        ),
        migrations.AddField(
            model_name='files',
            name='image_2',
            field=models.ImageField(default='', storage=FinalApp.models.RenameStorage1(), upload_to=''),
        ),
    ]
