# Generated by Django 4.0.4 on 2023-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0046_rename_name_userprofile_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
